### ISSUE TITLE
FR: Enhancements to tariff compare feature

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#1980]
**Is your feature request related to a problem? Please describe.**
Just tried out the new tariff compare feature, a brilliant addition Trefor, thanks for adding this, I think it'll be really useful.

A few observations/comments on using it for the first time:

1. suggest the iboost and carbon columns be suppressed if they are not configured in Predbat, in my case they are not, and are both always zero

![image](https://github.com/user-attachments/assets/dfe38282-51e1-4f89-8590-192a10738e5b)

2. Similarly, suppress actual(car) if a car isn't setup in apps.yaml, as I don't have one, the data is always the same as actual

~~3. I'm not really sure what Actual is showing me, its not the current cost, nor is it a projection~~

4. When running a manual compare, at 23:30 in my case the total figures include all of today's consumption plus the projection for tomorrow.  This gives really large projected values that aren't really useful.
Wouldn't happen with the midnight automatic comparison, but suggest that if a manual comparison is done a today value of zero be taken otherwise its a day and a part day comparison.

![image](https://github.com/user-attachments/assets/b25ff326-0d68-4bbb-9067-146fb716aaae)

5. The comparison appears to be of 'now' plus 24 hours, so running it at 23:30 it runs the comparison up to the same time tomorrow.
I suggest that the comparison needs to run for a longer time window (say mid-day the following day) even if its then truncated back to show just tomorrow's data.
The reason for this is illustrated on Cosy which I'm currently on.  There is a cheap rate charging period now from 22:00-00:00 but the predbat comparison doesn't do any charging in that period because there is no future load that will be consumed - so predbat (rightly) determines its not worth charging.
However of course in reality you would charge in that period to take advantage of the cheap rate period.

Manual compare run at 23:30:
![image](https://github.com/user-attachments/assets/b27dc9c1-9b45-44cb-ab97-ddb97e40fc52)

Edit:
The automatic compare run at 00:00 does not have this problem, charging is planned for the 22:00-00:00 Cosy slot:
![image](https://github.com/user-attachments/assets/21e8aeb9-d2bb-4a7b-b74e-ce5574fb5d69)

6. Thanks for finding all the different tariff URL's, that's a pain!
Can you add tracker and Economy 7 please

7. Linked to point 4, the manual comparison (run on 7/2) appears alongside the automatic comparison (run on 8/2), but since the manual comparison is of 'today'+24 hours whereas the automatic is from midnight (at zero cost)+24 hours the comparison graph values are distorted:
![image](https://github.com/user-attachments/assets/d5fb0e4b-2c88-40d4-a4de-617721851bb5)

If the manual comparison was just done of running the simulation for 24 hours from midnight tonight (with today costs zero'd out) then would not have this issue.

8. In the automatic midnight comparison there is a discrepancy between the costs presented in the table and the html plans shown below.

e.g. the current plan in the table has cost £902 but the projected cost is £8.69.   There is a similar difference on all of the other tariff comparisons between the top table and the bottom HTML charts:
![image](https://github.com/user-attachments/assets/fd3bd7da-b0a0-4ca4-bb7b-66d0930a2a55)
![image](https://github.com/user-attachments/assets/2f53f22f-e96f-4a0c-a4c5-93eb012a8843)

**Comment by WyndStryke** [comment]
My suggestion is this:

* A magic button to answer the eternal question "Why did it generate the plan like this?"

If the user clicks it, the system will create alternatives which each differ by a single system configuration, one at a time reverting to the default (maybe ignore the harmless ones).  So they can see the effect that each configuration setting had on their plan, whether large or small.

**Comment by springfall2008** [comment]
1. suggest the iboost and carbon columns be suppressed if they are not configured in Predbat, in my case they are not, and are both always zero

Done

2. Similarly, suppress actual(car) if a car isn't setup in apps.yaml, as I don't have one, the data is always the same as actual

Done

4. When running a manual compare, at 23:30 in my case the total figures include all of today's consumption plus the projection for tomorrow. This gives really large projected values that aren't really useful.
Wouldn't happen with the midnight automatic comparison, but suggest that if a manual comparison is done a today value of zero be taken otherwise its a day and a part day comparison.

I've changed the code to start a 0 for all comparisons now

5. The comparison appears to be of 'now' plus 24 hours, so running it at 23:30 it runs the comparison up to the same time tomorrow.
I suggest that the comparison needs to run for a longer time window (say mid-day the following day) even if its then truncated back to show just tomorrow's data.
The reason for this is illustrated on Cosy which I'm currently on. There is a cheap rate charging period now from 22:00-00:00 but the predbat comparison doesn't do any charging in that period because there is no future load that will be consumed - so predbat (rightly) determines its not worth charging.
However of course in reality you would charge in that period to take advantage of the cheap rate period.

Actually the comparison should run for 48 hours and then only count the next 24 hours to avoid odd issues like dumping the battery at the end of the period. It's possible something was broken here so I did make a change to ensure its always the case - please re-test.

6. Thanks for finding all the different tariff URL's, that's a pain!
Can you add tracker and Economy 7 please

I can find their economy 7 but its not really the same as you need a smart meter (snug)
Not sure what you mean by tracker, 3 monthly one?

7.Linked to point 4, the manual comparison (run on 7/2) appears alongside the automatic comparison (run on 8/2), but since the manual comparison is of 'today'+24 hours whereas the automatic is from midnight (at zero cost)+24 hours the comparison graph values are distorted:

The manual will only show at the end of the chart, it will be dropped on the next day in favour of the datapoint at midnight

**Comment by springfall2008** [comment]
https://github.com/springfall2008/batpred/releases/tag/v8.14.2

**Comment by gcoan** [comment]
> Thanks for finding all the different tariff URL's, that's a pain!
> Can you add tracker and Economy 7 please
> I can find their economy 7 but its not really the same as you need a smart meter (snug)
> Not sure what you mean by tracker, 3 monthly one?

Thanks for all the responses and bug fixes, I'll upgrade to the new release and let you know of any issues.

Economy 7 and Tracker don't appear to be on the list of product codes https://api.octopus.energy/v1/products/ 

By Tracker I meant the tariff is variable like Agile except it gives you a single daily price based upon wholesale rates. Its very similar to the SVR so TBH not worth including at the momment.
I see you added Snug, its and E7-like tariff but its for owners of specific electric storage heaters that Octopus can control remotely,  so similar to IOG for storage heaters.  Quite niche.

Here's the manual setup for Economy 7 with SEG:

```
- id: 'eco7_seg'
  name: 'Eco7 import/SEG export'
  rates_import:
    - start: "00:30:00"
      end: "07:30:00"
      rate: 13.52
    - start: "07:30:00"
      end: "00:30:00"
      rate: 32.24
  rates_export:
     - rate: 4.1
```

**Comment by PianSom** [comment]
I am not entirely convinced that showing pricing to the nearest 0.01p is (a) necessary or (b) accurate :)

Perhaps costs could be displayed like £4.27 rather than 427.31 [p]?

**Comment by gcoan** [comment]
> 2. Similarly, suppress actual(car) if a car isn't setup in apps.yaml, as I don't have one, the data is always the same as actual
> Done

Hi Trefor, am running 8.14.3.  Still seeing identical lines in the graph for actual and actual (no car):

![image](https://github.com/user-attachments/assets/ec706135-17f5-430e-83d8-e6ff5bf043cd)

> 8. In the automatic midnight comparison there is a discrepancy between the costs presented in the table and the html plans shown below.
e.g. the current plan in the table has cost £902 but the projected cost is £8.69. There is a similar difference on all of the other tariff comparisons between the top table and the bottom HTML charts:

I'm still seeing a difference between the figures in the summary table and the end cost in the plan:

![image](https://github.com/user-attachments/assets/697348c5-e45f-430d-8c6a-5456cbd15bb6)
![image](https://github.com/user-attachments/assets/a3eaba8b-7474-464d-957a-152146d233e3)

And agree, can we have the table formatted as £ and pence (or whatever current configured in apps.yaml), don't need 2dp.

Brilliant addition to predbat

**Comment by springfall2008** [comment]
The car line depends on 'car_charging_hold' being turned on or off rather than the number of cars, mostly as some people use that to remove data from other sources.

Can you show the differences, you only showed the table and not the end of plan?

**Comment by gcoan** [comment]
> The car line depends on 'car_charging_hold' being turned on or off rather than the number of cars, mostly as some people use that to remove data from other sources.

Thanks, turned car charging hold off and the car line disappears. 


> Can you show the differences, you only showed the table and not the end of plan?

Here's the table and plan for current and Cosy (but there is a similar difference on all the tariff plans):

![image](https://github.com/user-attachments/assets/a4373382-300b-4464-a95f-37e84fc81b5f)
![image](https://github.com/user-attachments/assets/d1d04857-908c-4478-939d-beabedb5fc9b)
![image](https://github.com/user-attachments/assets/0467f34d-3470-4aed-83f0-69cf6c7c6a79)
![image](https://github.com/user-attachments/assets/2ed44fe5-26eb-4105-92ed-cd43deb2ade0)
![image](https://github.com/user-attachments/assets/5357430f-47df-47a8-974a-93c3df3cb916)
![image](https://github.com/user-attachments/assets/10be9c33-8e59-43a6-b453-3eea04c34b47)
![image](https://github.com/user-attachments/assets/21381192-e29f-4616-982c-b45218716e3e)

**Comment by springfall2008** [comment]
Okay, that's because the pounds value in the HTML plan is at the start of the 30 minute slot and the cost in the compare table is at the end of the period.

**Comment by springfall2008** [comment]
New release made changing to £'s and also including now re-planning the car charging if enabled

**Comment by gcoan** [comment]
new release looks good thanks Trefor
