### ISSUE TITLE
Exception Error since v8.26 (Predbat compare)

### ISSUE THREAD

**Issue by jrwm47** [springfall2008/batpred#2813]
Since the 8.26 upgrade, I have been getting an Exception Error:

41874  2025-10-23 11:13:54.845421: Error:
41873  2025-10-23 11:13:54.845048: Info: record_status Error: Exception raised
41871  ValueError
41870  raise ValueError
41858  2025-10-23 11:13:54.826064: Error: Traceback (most recent call last):
41857  2025-10-23 11:13:54.810753: Error: Exception raised
41856  2025-10-23 11:13:54.810473: Error: Failure to fetch history for predbat.compare_tariff_flux

The problem seems to be in the _Compare_ feature which I have been using to associate Agile v Flux tariffs to current season and weather conditions. Full relevant _apps.yaml.bad_ is attached, with Compare section based on the example in the current Docs (Oct 25). Commenting this section out entirely makes Error go away.

This issue may relate to Geoff Coan's feature request #2726 about Octopus frequently changing tariff URLs. 

<img width="452" height="385" alt="Image" src="https://github.com/user-attachments/assets/12a0a452-bccb-45d3-9697-0ce4c1945258" />

[apps.yaml.bad.txt](https://github.com/user-attachments/files/23096405/apps.yaml.bad.txt)

**Comment by gcoan** [comment]
That's strange.

The feature request is to add better validation of the octopus url as at the moment if they are wrong then they fail silently and you just get gaps in the compare. 

The compare url in the documentation are all correct, I checked them.
But just to prove, can you comment the compare back in except for flux and see if it works ok?

I suspect that your problem is caused by #2760 which has a fix that'll be in the next release

**Comment by jrwm47** [comment]
Many thanks,

Tried what you suggest:
- copied entire Compare example from October Docs to apps.yaml
- commented out id: 'flux' section
- changed to region to H
- restarted
Exception Error returns, this time reporting - 'Failure to fetch history for predbat.compare_tariff_agile_fixed'

I will revert to the workaround until the release dealing with #2760 becomes available and let you know if that fixes the problem.

JM

<img width="1404" height="564" alt="Image" src="https://github.com/user-attachments/assets/756cbbf1-68ce-4add-816e-0564d62dc2bd" />

**Comment by gcoan** [comment]
thanks for the test

its a bit strange that flux initially failed when it wasn't the first compare tariff in your apps.yaml.  agile_fixed is, so I'd have expected that to fail every time

can I confirm, the graph that's underneath the table, do you see any data in that, other than the right-most (most recent) comparison?

my guess is that you're suffering from 2760 which causes a HA error (due to excessive sensor size) when writing the compare sensor to the HA database (if you look in system/logs at around midnight, you'll see the error).
And this has been occurring for 10 days or so, so all the compare sensor history has now expired off the graph.

And when compare next runs, there is no history, hence the crash?  Which suggests that there is still a problem with the compare code that I will need to look at.
Could you post a more complete predbat logfile from around midnight when the crash occurs.

I will take a look at the code, might be able to create a patch to fix it

**Comment by springfall2008** [comment]
Can you attached the logfile?

**Comment by jrwm47** [comment]
Good Morning Both, and many thanks for looking at this issue.

I'm afraid I'm not a night bird so I didn't see your comments until this morning. I also note that v8.26.2 is now available but I've held off installing it so I can perhaps help with debugging.

As requested, I:

1. reactivated the Compare function in apps.yaml

  dno_region: "H"
  compare_list:
    - id: 'current'
      name: 'Current Tariff'
    - id: 'cap_seg'
      name: 'Price cap import/SEG export'
      rates_import:
        - rate: 24.86
      rates_export:
        - rate: 4.1
    - id: 'flux'
      name: 'Flux import/Export'
      rates_import_octopus_url: 'https://api.octopus.energy/v1/products/FLUX-IMPORT-23-02-14/electricity-tariffs/E-1R-FLUX-IMPORT-23-02-14-{dno_region}/standard-unit-rates'
      rates_export_octopus_url: 'https://api.octopus.energy/v1/products/FLUX-EXPORT-23-02-14/electricity-tariffs/E-1R-FLUX-EXPORT-23-02-14-{dno_region}/standard-unit-rates'

2. noted that , following predbat restart, the Exception Error re-appeared
3. noted that the Compare report says it last ran at midnight 2 days ago, so I clicked the "Compare now" button. That was an hour ago but it still hasn't updated and says it's still "Running.."
4. downloaded and will attach predbat log files plus some screen shots

I'll stay on v8.26.1 and restore the Compare-commented-out workaround until you let me know whether I can be of any further help.

I also attach, for anyone who hasn't seen it working, 2 nice screenshots of predbat doing arbitrage with today's good Agile import/export pricing.

JM
HA 2025.8.3
predbat v8.26.1
rpi4-64

<img width="1458" height="1139" alt="Image" src="https://github.com/user-attachments/assets/fac83706-3020-445e-bf65-fd5f0b11bdef" />

<img width="676" height="903" alt="Image" src="https://github.com/user-attachments/assets/d169d13d-b7b6-418d-a8d7-a038c16d4418" />

<img width="1524" height="1092" alt="Image" src="https://github.com/user-attachments/assets/81897807-2988-4f4d-90f8-305374822a6c" />

<img width="297" height="95" alt="Image" src="https://github.com/user-attachments/assets/bc6ac695-8e29-4505-9e8b-c102cb77831d" />

[predbat.log](https://github.com/user-attachments/files/23120198/predbat.log)

[predbat.1.log](https://github.com/user-attachments/files/23120199/predbat.1.log)

[predbat.2.log](https://github.com/user-attachments/files/23120203/predbat.2.log)

**Comment by gcoan** [comment]
> I'll stay on v8.26.1 and restore the Compare-commented-out workaround until you let me know whether I can be of any further help.

I'd suggest you do upgrade to 8.26.2.  This version includes a fix to the compare function so it doesn't save excessive data to the HA database, earlier versions were doing this which was causing history to not be written and thus the compare graph was empty.

If you can upgrade,  check predbat runs OK with the compare commented out,  and all going well can you uncomment the compare lines, force a manual compare (click the button) and see if it works.  My guess is that it won't, there is a bug in predbat not handling missing history compare data, but this should prove it.  Either way, can you provide the logs for this compare run.

If compare is running OK you should see the last compare time progressively changing for each tariff.  

thanks for trying to help find the problem

**Comment by PhillyGilly** [comment]
I can run OK on 8.25.14 but get exception errors on 8.26
Here are the last few lines of my log on 8.26.2:
```
2025-10-24 16:15:04.237645: - Your estimated bill for today is £-2.35 and tomorrow is £-3.98
2025-10-24 16:15:04.237668: - Import rates are very expensive (5.2p - 35.6p) for the next 6 and a quarter hours and then expensive (2.1p) for the next 1 hour.
2025-10-24 16:15:04.237679: - The battery is currently at 73% and is force exporting to 4% for the next 3 and three quarters hours.
2025-10-24 16:15:04.237690: - For the next 1 and a half hours there will be hardly any solar generation and then it will decrease.
2025-10-24 16:15:04.237700: - You will run out of battery in 3 and a half hours.
2025-10-24 16:15:04.237710: - Your next charge slot will be in 7 and a quarter hours where import rates will be cheap (1.1p).
2025-10-24 16:15:04.237720: 
2025-10-24 16:15:04.276736: Web interface history update
2025-10-24 16:15:04.378424: Error: Exception raised 0
2025-10-24 16:15:04.381088: Error: Traceback (most recent call last):
  File "/config/predbat.py", line 1496, in run_time_loop
    self.update_pred(scheduled=True)
  File "/config/predbat.py", line 697, in update_pred
    recompute = self.calculate_plan(recompute=recompute)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/plan.py", line 1149, in calculate_plan
    self.components.get_component("web").history_update()
  File "/config/web.py", line 130, in history_update
    self.compare_hist[id]["cost"] = self.base.history_attribute(self.base.get_history_wrapper(result["entity_id"], 28), daily=True, pounds=True)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/predbat.py", line 308, in get_history_wrapper
    history = ha_history.get_history(entity_id, days=days, tracked=tracked)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/ha.py", line 111, in get_history
    history_data = history_data[0]
                   ~~~~~~~~~~~~^^^
KeyError: 0

2025-10-24 16:15:04.400903: Info: record_status Error: Exception raised 0
2025-10-24 16:15:04.400994: Error: 0
2025-10-24 16:16:11.226458: Error: HAHistory exception in update loop: 0
2025-10-24 16:16:11.227050: Error: Traceback (most recent call last):
  File "/config/ha.py", line 210, in start
    history_data = history_data[0]
                   ~~~~~~~~~~~~^^^
KeyError: 0
```

**Comment by jrwm47** [comment]
Geoff, as requested I have:

1. updated to v8.26.2 with Compare commented out - no Exception errors
2. uncommented Compare section including: current, cap_seg, agile_fixed, agile_agile, flux, iflux. On restart, as you predicted, Exception errors on Dashboard and in log (attached). Compare results still dated from 2 days ago. Screenshot attached.
3. clicked Compare Now button.  "Running" message appears and remains indefinitely. Compare results not updated.

I will revert to my "good" apps.yaml with Compare section commented out and await news and/or advice.

Cheers, Julian

[predbat.log](https://github.com/user-attachments/files/23130220/predbat.log)

<img width="1512" height="1195" alt="Image" src="https://github.com/user-attachments/assets/a6ceb8a3-496a-4f03-9d3b-02b4ed9797ce" />

**Comment by gcoan** [comment]
Julian

Try 8.26.3, this might fix the compare bug for you

https://github.com/springfall2008/batpred/releases/tag/v8.26.3

Cheers

**Comment by jrwm47** [comment]
Updated to v8.26.4.   Presume that includes changes in v8.26.3.

Exception Error still there  ...

2025-10-24 22:11:19.882743: Web interface history update
2025-10-24 22:11:20.754958: Error: Failure to fetch history for predbat.compare_tariff_agile_fixed
2025-10-24 22:11:20.755197: Error: Exception raised 
2025-10-24 22:11:20.792814: Error: Traceback (most recent call last):
  File "/config/predbat.py", line 1438, in update_time_loop
    self.update_pred(scheduled=False)
  File "/config/predbat.py", line 697, in update_pred
    recompute = self.calculate_plan(recompute=recompute)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/plan.py", line 1149, in calculate_plan
    self.components.get_component("web").history_update()
  File "/config/web.py", line 130, in history_update
    self.compare_hist[id]["cost"] = self.base.history_attribute(self.base.get_history_wrapper(result["entity_id"], 28), daily=True, pounds=True)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/predbat.py", line 314, in get_history_wrapper
    raise ValueError
ValueError

2025-10-24 22:11:20.814059: Info: record_status Error: Exception raised 
2025-10-24 22:11:20.814299: Error: 


which to my inexpert eye looks like what PhillyGilly reported above.

 Julian

**Comment by PhillyGilly** [comment]
I can confirm that I have the Exception Error on 26.4

**Comment by springfall2008** [comment]
There was a fix for compare crashes in v8.27.9 but the original cause is bad compare URLs

**Comment by PhillyGilly** [comment]
OK hands up I was using an out-of-date Agile Export tariff. But I have now copied the codes verbatim from the documentation
```
- id: 'agile_agile'
      name: 'Agile import/Agile export'
      rates_import_octopus_url: 'https://api.octopus.energy/v1/products/AGILE-24-10-01/electricity-tariffs/E-1R-AGILE-24-10-01-{dno_region}/standard-unit-rates/'
      rates_export_octopus_url: 'https://api.octopus.energy/v1/products/AGILE-OUTGOING-19-05-13/electricity-tariffs/E-1R-AGILE-OUTGOING-19-05-13-{dno_region}/standard-unit-rates/'
```

But I'm still getting the exception error. on 8.27.12.

<img width="1067" height="375" alt="Image" src="https://github.com/user-attachments/assets/7405277c-0ff6-41ed-8f3b-1ce59fa65f6d" />

(also any ideas why I'm getting regular big gaps in my historical day data?)

**Comment by gcoan** [comment]
> also any ideas why I'm getting regular big gaps in my historical day data?)

do you have a givenergy inverter?  There have been problems with givtcp 3.4 not presenting the load energy today sensor properly which is causing predbat problems.

Have a look at your sensor history

**Comment by PhillyGilly** [comment]
> > also any ideas why I'm getting regular big gaps in my historical day data?)
> 
> do you have a givenergy inverter? There have been problems with givtcp 3.4 not presenting the load energy today sensor properly which is causing predbat problems.
> 
> Have a look at your sensor history

Thanks. Yes that is definitely part of it. I moverd from 3.4 to 3.5 on the 9th November and it made a difference.
However I still have the 12th as a 3.5 day where the reset didn't work. I'll keep an eye on it and maybe post int the GivTCP issues.

<img width="1707" height="445" alt="Image" src="https://github.com/user-attachments/assets/2b1f166c-72ff-46d0-b992-99b3f31378b2" />

**Comment by gcoan** [comment]
> Thanks. Yes that is definitely part of it. I moverd from 3.4 to 3.5 on the 9th November and it made a difference.
> However I still have the 12th as a 3.5 day where the reset didn't work. I'll keep an eye on it and maybe post int the GivTCP issues.

I'm still contributing to the GivTCP issue on midnight reset, it's a lot better with 3.5, but not perfect

Issue is https://github.com/britkat1980/giv_tcp/issues/441 if you want to add your experience to the chain

**Comment by jrwm47** [comment]
It does seem a lot of us GE/predbat users are getting these problems. When I first opened this Issue several weeks ago, the focus was on Exception Errors with predbat Compare but, as Geoff says, it has since moved to GivTCP.

As a temporary workaround I am now running predbat with Load, Import, Export, and PV histories picked up from the GE portal. It appears to be working fine, including daily Compare runs with several Octopus tariffs. I am also running GivTCP 3.5 and still occasionally seeing the same midnight reset funnies - which predbat now ignores.

I am beginning to suspect some sort of processor resource midnight fight between predbat Compare and GivTCP. I have checked process and memory in my RPi4 at midnight and for a few minutes thereafter using HA System and Linux htop. Peak activity in one or more cores regularly hits 98%. This shouldn't be a problem but there it is.

Cheers to those trying to solve the problem, Julian

**Comment by gcoan** [comment]
I think the crashing problem started off with the Compare URL's stopping working and Predbat compare would end up with gaps in the compare history which when those accumulate to being a week or so long, cause Predbat to crash.

There's separately an issue with GivTCP 3.4 not creating load history properly and in particular not resetting at midnight, and again this is causing predbat problems.

Correcting the compare URLs and upgrading to GivTCP 3.5 fixes most of these problems going forward but doesn't resolve the compare or load history (and there are still remaining midnight spike problems).  I suspect one of these history problems is the cause of the remaining predbat crash.

If you've found GE cloud data resolves this then great, we have a workaround.

I have also noticed that the PC I have running HA runs really hard at midnight when the Predbat compare runs.  I can hear it every night as the PC fans spin up to keep it cool.  It only lasts 5 minutes or so but it happens consistently every night.
Interesting idea about the predbat compare and givtcp daily resets could be conflicting for CPU resources as they both run at midnight. Wonder if reducing the CPU threads for Predbat (in apps.yaml) might help mitigate this?

**Comment by ppmt** [comment]
Just to jump on this thread I experienced the same problem today.
I have been using the compare option for a few weeks without problem. I was only using the tariff from Octopus.

Yesterday I added a new tariff (Good Energy) to see if it is that good. and this morning I see this error.

```
38495	raise ValueError
38483	2025-11-16 10:40:02.754924: Error: Traceback (most recent call last):
38482	2025-11-16 10:40:02.753682: Error: Exception raised
38481	2025-11-16 10:40:02.753594: Error: Failure to fetch history for predbat.compare_tariff_Good Energy EV
38369	2025-11-16 10:35:02.170617: Error:
38368	2025-11-16 10:35:02.170556: Info: record_status Error: Exception raised
38366	ValueError


```
```
  dno_region: "E"
  compare_list:
    - id: 'current'
      name: 'Agile import/Fixed export'
      rates_import_octopus_url: 'https://api.octopus.energy/v1/products/AGILE-24-10-01/electricity-tariffs/E-1R-AGILE-24-10-01-{dno_region}/standard-unit-rates/'
      rates_export_octopus_url: 'https://api.octopus.energy/v1/products/OUTGOING-VAR-24-10-26/electricity-tariffs/E-1R-OUTGOING-VAR-24-10-26-{dno_region}/standard-unit-rates/'
    - id: 'agile_agile'
      name: 'Agile import/Agile export'
      rates_import_octopus_url: 'https://api.octopus.energy/v1/products/AGILE-24-10-01/electricity-tariffs/E-1R-AGILE-24-10-01-{dno_region}/standard-unit-rates/'
      rates_export_octopus_url: 'https://api.octopus.energy/v1/products/AGILE-OUTGOING-19-05-13/electricity-tariffs/E-1R-AGILE-OUTGOING-19-05-13-{dno_region}/standard-unit-rates/'
    - id: 'go_fixed'
      name: 'GO import/Fixed export'
      rates_import_octopus_url: 'https://api.octopus.energy/v1/products/GO-VAR-22-10-14/electricity-tariffs/E-1R-GO-VAR-22-10-14-{dno_region}/standard-unit-rates/'
      rates_export_octopus_url: 'https://api.octopus.energy/v1/products/OUTGOING-VAR-24-10-26/electricity-tariffs/E-1R-OUTGOING-VAR-24-10-26-{dno_region}/standard-unit-rates/'
    - id: 'flux'
      name: 'Flux import/Export'
      rates_import_octopus_url: 'https://api.octopus.energy/v1/products/FLUX-IMPORT-23-02-14/electricity-tariffs/E-1R-FLUX-IMPORT-23-02-14-{dno_region}/standard-unit-rates'
      rates_export_octopus_url: 'https://api.octopus.energy/v1/products/FLUX-EXPORT-23-02-14/electricity-tariffs/E-1R-FLUX-EXPORT-23-02-14-{dno_region}/standard-unit-rates'
    - id: 'Good Energy EV'
      name: 'Good Energy EV/Fixed export'
      rates_import:
        - rate: 6.6
          start: "00:00:00"
          end: "05:00:00"
        - rate: 29.15
          start: "05:00:00"
          end: "00:00:00"
      rates_export:
        - rate: 15
```

**Comment by gcoan** [comment]
> Just to jump on this thread I experienced the same problem today.
> I have been using the compare option for a few weeks without problem. I was only using the tariff from Octopus.

thanks that's a useful extra bit of evidence @ppmt, looks like the compare is expecting there always to be history present, which of course for a new compare there won't ever be

presumably if you comment the good energy entry out of apps.yaml then the compare runs ok?

could you post a larger snippet of your logs showing the lines leading up to and including the crash

it does look like a bug @springfall2008

**Comment by ppmt** [comment]
Yes as soon as I commented out the tariff the fault disappeared.

I have added a log I took from the Home Assistant Addons. Hope this help.
```

2025-11-16 10:30:02.362153: Error: Failure to fetch history for predbat.compare_tariff_Good Energy EV
2025-11-16 10:30:02.362216: Error: Exception raised 
2025-11-16 10:30:02.363245: Error: Traceback (most recent call last):
  File "/config/predbat.py", line 1520, in run_time_loop
    self.update_pred(scheduled=True)
  File "/config/predbat.py", line 689, in update_pred
    recompute = self.calculate_plan(recompute=recompute)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/plan.py", line 1152, in calculate_plan
    self.components.get_component("web").history_update()
  File "/config/web.py", line 131, in history_update
    self.compare_hist[id]["cost"] = history_attribute(self.base.get_history_wrapper(result["entity_id"], 28), daily=True, pounds=True)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/predbat.py", line 315, in get_history_wrapper
    raise ValueError
ValueError

2025-11-16 10:30:02.374459: Info: record_status Error: Exception raised 
2025-11-16 10:30:02.374526: Error: 
Traceback (most recent call last):
  File "/config/hass.py", line 191, in timer_tick
    item["callback"](None)
  File "/config/predbat.py", line 1525, in run_time_loop
    raise e
  File "/config/predbat.py", line 1520, in run_time_loop
    self.update_pred(scheduled=True)
  File "/config/predbat.py", line 689, in update_pred
    recompute = self.calculate_plan(recompute=recompute)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/plan.py", line 1152, in calculate_plan
    self.components.get_component("web").history_update()
  File "/config/web.py", line 131, in history_update
    self.compare_hist[id]["cost"] = history_attribute(self.base.get_history_wrapper(result["entity_id"], 28), daily=True, pounds=True)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/predbat.py", line 315, in get_history_wrapper
    raise ValueError
ValueError


```

**Comment by gcoan** [comment]
@ppmt I have a potential fix for you

If you can edit the web.py file in your predbat addon directory, you are looking for lines about 125-132 which currently look like this:

```
        for item in compare_list:
            id = item.get("id", None)
            if id and self.base.comparison:
                self.compare_hist[id] = {}
                result = self.base.comparison.get_comparison(id)
                if result:
                    self.compare_hist[id]["cost"] = history_attribute(self.base.get_history_wrapper(result["entity_id"], 28), daily=True, pounds=True)
                    self.compare_hist[id]["metric"] = history_attribute(self.base.get_history_wrapper(result["entity_id"], 28), state_key="metric", attributes=True, daily=True, pounds=True)
```

The fix is to change the last two lines to be as follows:

```
                    self.compare_hist[id]["cost"] = history_attribute(self.base.get_history_wrapper(result["entity_id"], 28, required=False), daily=True, pounds=True)
                    self.compare_hist[id]["metric"] = history_attribute(self.base.get_history_wrapper(result["entity_id"], 28, required=False), state_key="metric", attributes=True, daily=True, pounds=True)
```

You are adding ", required=False" just after the 28 and before the close bracket.

This tells predbat to not error if it doesn't get history for the compare entity id.

I have not tested this, but it looks like a fair fix.  Let me know

**Comment by ppmt** [comment]
I have implemented your fix. It seems to work.

I first changed the web.py and restarted the app. It worked.

Then I reactivated the faulty tariff and restarted again. It still works.

I will keep an eye to see if anything changes.

Thanks for the fix

**Comment by gcoan** [comment]
Great.  If you can keep an eye on it overnight, check the logs for the midnight compare and no unexpected issues, and if all OK I will merge it into my next PR

**Comment by ppmt** [comment]
Here is what I can see in the logs around midnight...
And no errors reported in the web ui either

```
2025-11-16 23:50:23.074892: Info: record_status Demand
2025-11-16 23:55:03.251331: Info: record_status Demand
2025-11-17 00:00:30.842661: Info: record_status Demand
2025-11-17 00:05:03.283127: Info: record_status Demand
2025-11-17 00:08:07.086911: Info: HAHistory: Pruning history data
2025-11-17 00:10:20.146174: Info: record_status Demand
2025-11-17 00:15:02.987738: Info: record_status Demand
2025-11-17 00:20:20.931179: Info: record_status Demand
2025-11-17 00:25:02.942468: Info: record_status Demand
2025-11-17 00:30:21.490418: Info: record_status Demand
2025-11-17 00:35:03.307494: Info: record_status Demand
2025-11-17 00:40:21.959711: Info: record_status Demand
2025-11-17 00:45:03.022014: Info: record_status Demand
2025-11-17 00:50:20.405466: Info: record_status Demand
2025-11-17 00:55:03.240556: Info: record_status Demand
2025-11-17 01:00:21.566311: Info: record_status Demand
```

**Comment by gcoan** [comment]
Thanks @ppmt I'm including this in my next PR

@PhillyGilly @jrwm47 see fix details above

**Comment by ppmt** [comment]
Just a comment about that issue. I tought it was fixed but since the last couple of version (not sure exactly) but definitely on 8.28.4 the compare section is failing again but differently this time
I was getting a server error on that page with the following in the logs

```
2025-11-27 09:56:13.189511: Error: Failure to fetch history for predbat.compare_tariff_Good Energy EV
Error handling request from 172.30.32.2
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/aiohttp/web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/web.py", line 2433, in html_compare
    compare_hist[id]["cost"] = history_attribute(self.get_history_wrapper(result["entity_id"], 28), daily=True, pounds=True)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/component_base.py", line 218, in get_history_wrapper
    return self.base.get_history_wrapper(entity_id, days=days, required=required, tracked=tracked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/predbat.py", line 315, in get_history_wrapper
    raise ValueError
ValueError
2025-11-27 09:56:44.453940: Error: Failure to fetch history for predbat.compare_tariff_Good Energy EV
Error handling request from 172.30.32.2
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/aiohttp/web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/web.py", line 2433, in html_compare
    compare_hist[id]["cost"] = history_attribute(self.get_history_wrapper(result["entity_id"], 28), daily=True, pounds=True)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/component_base.py", line 218, in get_history_wrapper
    return self.base.get_history_wrapper(entity_id, days=days, required=required, tracked=tracked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/predbat.py", line 315, in get_history_wrapper
    raise ValueError
ValueError
2025-11-27 09:56:50.266477: Error: Failure to fetch history for predbat.compare_tariff_Good Energy EV
Error handling request from 172.30.32.2
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/aiohttp/web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/web.py", line 2433, in html_compare
    compare_hist[id]["cost"] = history_attribute(self.get_history_wrapper(result["entity_id"], 28), daily=True, pounds=True)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/component_base.py", line 218, in get_history_wrapper
    return self.base.get_history_wrapper(entity_id, days=days, required=required, tracked=tracked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/predbat.py", line 315, in get_history_wrapper
    raise ValueError
ValueError
```

Checking in web.py (line 2433/2434) I can see that the  Required=False has gone. Adding it back fixed the issue.

**Comment by gcoan** [comment]
> Checking in web.py (line 2433/2434) I can see that the Required=False has gone. Adding it back fixed the issue.

that code change is still in my fork, its not yet PR'd in.  Am working on some other enhancements and a seemingly endless list of changes to support more inverter types, I could do with that lot steadying down to raise the PR.

So if you upgrade you will have to re-apply the fix (for now)

**Comment by ppmt** [comment]
Fair enough. I was under the impression I didn't have to do it for some time but may be I just didn't check compare for some time :D

Sorry for the disturb

**Comment by gcoan** [comment]
> Fair enough. I was under the impression I didn't have to do it for some time but may be I just didn't check compare for some time :D
> 
> Sorry for the disturb

no worries

TBH I am surprised that you got the error still, once the compare history had built up the code change shouldn't have been necessary.  Anyway the fix still works and its in my next PR

**Comment by ppmt** [comment]
This was not the same error. All seem to work until you go on the compare page and then it displayed a Web server Error.

With no real way to go back to the other tab that I could find. I had to restart the addons for that.

Happy to reproduce if it can help you
