### ISSUE TITLE
2nd cars not charging as expected - predbat_car_charging_manual_soc_kwh does not increase

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#2937]
### Discussed in https://github.com/springfall2008/batpred/discussions/2890

<div type='discussions-op-text'>

<sup>Originally posted by **ppmt** November 10, 2025</sup>
a few weeks ago I configure predbat for my new car and all worked well. Now we have 2 electric cars and I just can't get it to charge as I want. 

I suspect it is a bad config on my side but.... 
Here is my config for both cars
<img width="1022" height="573" alt="Screenshot From 2025-11-09 20-31-52" src="https://github.com/user-attachments/assets/f934c2c8-70be-40b9-9424-9f7ca5ca13fa" />

Le me know if this is not enough info. 

So when I plug a car I have a switch which I use to say which car is connected. When I select the first one (lulu) then it works perfectly. I can set the initial SOC (none of my car can report it!), I can also say how much I want to charge the car and predbat does its magic and all is good.

When I select the second one (ioniq) and do the same it behaves completely differently. whatever initial SOC I enter predbat seems to assume it needs to charge the car from 0%. That is annoying but we could work around that.
So If I work around and say to charge 10k it will select the correct amount of slot to deliver the 10k.

What is not good is that the sensor input_number.predbat_car_charging_manual_soc_kwh does not increase as the car is charging. So as far as predbat is concerned the car is not charging and it constantly reschedules new slow. The result is that the car get overcharged until it is full.

 It works perfectly when I charge the first car. I can see that input_number.predbat_car_charging_manual_soc_kwh is increasing as the car is charging.
 
 As I said I suspect I have a bad config but I can't work it out and would appreciate some guidance.
 
 Thank you</div>

**Comment by gcoan** [comment]
@ppmt creating an issue to track development of this enhancement

**Comment by ppmt** [comment]
Thank you. Looking forward to test !

**Comment by gcoan** [comment]
@ppmt I have been thinking about this tonight, and I have a quick fix that I think will work for you, but isn't the full fix.

If you can edit the predbat.py file in the predbat addon directory, around like 868, change it from:

```
        # Car SoC increment
        if scheduled:
            for car_n in range(self.num_cars):
                if (car_n == 0) and self.car_charging_manual_soc:
                    self.log("Car charging Manual SoC current is {} next is {}".format(self.car_charging_soc[car_n], self.car_charging_soc_next[car_n]))
                    if self.car_charging_soc_next[car_n] is not None:
                        self.expose_config("car_charging_manual_soc_kwh", dp3(self.car_charging_soc_next[car_n]))

```

to:

```
        # Car SoC increment
        if scheduled:
            for car_n in range(self.num_cars):
                if self.car_charging_manual_soc:
                    self.log("Car charging Manual SoC current is {} next is {}".format(self.car_charging_soc[car_n], self.car_charging_soc_next[car_n]))
                    if self.car_charging_soc_next[car_n] is not None:
                        self.expose_config("car_charging_manual_soc_kwh", dp3(self.car_charging_soc_next[car_n]))
```

you're removing the '(car_n == 0) and' bit from the if statement so car_charging_manual_soc_kwh will increment for either of your cars charging

I had hoped that this could be the simple permanent fix, but thinking more about it, it can't.  It will work for you because you have just one EV charging and exclusive charging setup, but for people who have two EV chargers then car charging manual soc kwh will increment when both cars are charging, and will be a meaningless number.  Moreover there is no way to set a manual soc for the second car as there is only one manual_soc_kwh

To do this properly I think we need multiple of switch.predbat_car_charging_manual_soc and multiple of  input_number.predbat_car_charging_manual_soc_kwh, one for each car

that's going to take far more detailed code surgery

**Comment by ppmt** [comment]
I implemented the changes but unfortunately it doesn't help. In fact it stopped the input_number.predbat_car_charging_manual_soc_kwh to increase completely for both car.

I tried to use the config for the 2nd car and it didn't increase and when I switched it to the first car it also didn't charge.

After rolling back the change the first car starting increasing again.

**Comment by gcoan** [comment]
weird.  can you attach the logfile please, ideally covering the before, after and then reverted change.  I want to see whether it thought they were charging

thanks for trying anyway. I hoped it was a quick workaround, surprised it didn't work

**Comment by ppmt** [comment]
I will try again tomorrow to provide the logs your are asking.

I have some but it is messy and I can't pinpoint the different stage since I didn't take note of the time.

**Comment by ppmt** [comment]
Hello,
I have done some more test trying to collect logs. I was filtering on the word CAR to limit the size. I hope that will be ok.

The car connected is the second car in the config
It started charging at 20h30 if you go down the file it includes the first update at 20:35 and you can see the SOC didn't increase.

[predbat_before_implementing_fix.txt](https://github.com/user-attachments/files/23613974/predbat_before_implementing_fix.txt)

The file below is after I updated the predbat.py file with your modif. I restart predbat and initially it looked good and I could actually see the SOC increasing at the first update (20:50)  but then something strange happened at the second and 3rd update (20:55 and 21:00) and you can see that the SOC is actually decreasing

[predbat_after_implementing_fix.txt](https://github.com/user-attachments/files/23614049/predbat_after_implementing_fix.txt)


Let me know if you need more detailed log

**Comment by gcoan** [comment]
Thanks.  Can hold onto a full copy of the predbat log in case I need it.

Looking at log 2, I don't see anything after 20:51, so no car soc decreasing at 20:55.  Have you missed it out?

One thing I noticed, you are getting a warning:

32590	2025-11-18 20:30:49.632859: Warn: Service call notify/mobile_app_treforsiphone12_2 data {'message': 'Predbat status change to: Hold for car'} failed with response None

This is because your apps.yaml has Trefor (the author of Predbat)'s mobile in.  You need to replace this with your mobile id (when you install the HA companion app this will be created)

**Comment by ppmt** [comment]
The log is split in 3 section. there are further down below in the file. 

Regarding the warning it is kind of on purpose. I was receiving too many notification so emptied the id and somehow it reverted back to Trefor's id :)

I will keep a copy of the full log.

**Comment by gcoan** [comment]
> The log is split in 3 section. there are further down below in the file.

thanks. stupid me, didn't scroll down far enough.  thought I had reached the bottom of the file.

I think you are misreading the lines in the log.  You have to read them in reverse order, and since we have taken the car_n bit out you are getting one line per car configured.  

car 2 SoC increases:
34038	2025-11-18 20:51:02.745311: Car charging Manual SoC current is 1.212 next is 1.772
car 1 SoC unchanged:
34037	2025-11-18 20:51:02.745156: Car charging Manual SoC current is 1.212 next is 1.212

car 2 SoC increases:
34348	2025-11-18 20:55:22.141998: Car charging Manual SoC current is 1.212 next is 1.771
car 1 SoC unchanged:
34347	2025-11-18 20:55:22.141850: Car charging Manual SoC current is 1.772 next is 1.772

car 2 SoC increases:
34494	2025-11-18 21:00:03.579325: Car charging Manual SoC current is 1.212 next is 1.709
car 1 SoC unchanged:
34493	2025-11-18 21:00:03.579198: Car charging Manual SoC current is 1.771 next is 1.771
3

But remember there's still only a single car charging manual soc kwh so each time around the car 2 SoC is getting reported as car 1 SoC, which doesn't change as car 1 is not charging.

As I said it was a quick fix, its not perfect, it needs a separate manual soc 2 but I think it is still working OK.

Here's a further change to make that will make it a bit clearer, replace the self.log line with the version below which now includes the car number:

```
        # Car SoC increment
        if scheduled:
            for car_n in range(self.num_cars):
                if self.car_charging_manual_soc:
                    self.log("Car {} charging Manual SoC current is {} next is {}".format(car_n, self.car_charging_soc[car_n], self.car_charging_soc_next[car_n]))
                    if self.car_charging_soc_next[car_n] is not None:
                        self.expose_config("car_charging_manual_soc_kwh", dp3(self.car_charging_soc_next[car_n]))
```

So if you look at the line corresponding to the car that is charging I think it'll make sense.  The non-charging car soc is meaningless, ignore it

**Comment by ppmt** [comment]
I did another charge of my second car last night and I still think something is not right. I will try to explain.

So my battery was down to 10% so decided to charge it to 95% (so not quite full). Predbat after doing its calculation decided that the car should charge from 3h30 to about 7h30 (can't quite remember). This would have added about 35kw of power.

I let it running and went to bed. This morning checking the logs it looks like the car charge more or less all night from around 23:30 until just before 8am.
The car ended being fully charged.

As you can see from below it seems that Predbat didn't "see" that the car was charging or rather that the manual SOC kept being reset every 5 minutes.
This is a grep of the logs (I have the full log if you want them)

```
2025-11-19 23:10:19.876573: Car 0 charging Manual SoC current is 4.04 next is 4.04
2025-11-19 23:10:19.884422: Car 1 charging Manual SoC current is 4.04 next is 4.04
2025-11-19 23:15:03.606381: Car 0 charging Manual SoC current is 4.04 next is 4.04
2025-11-19 23:15:03.606537: Car 1 charging Manual SoC current is 4.04 next is 4.04
2025-11-19 23:20:23.671955: Car 0 charging Manual SoC current is 4.04 next is 4.04
2025-11-19 23:20:23.676368: Car 1 charging Manual SoC current is 4.04 next is 4.04
2025-11-19 23:25:03.262668: Car 0 charging Manual SoC current is 4.04 next is 4.04
2025-11-19 23:25:03.262815: Car 1 charging Manual SoC current is 4.04 next is 4.04
2025-11-19 23:30:58.978861: Car 0 charging Manual SoC current is 4.04 next is 4.04
2025-11-19 23:30:58.979034: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-19 23:35:03.405656: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-19 23:35:03.405809: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-19 23:40:14.576929: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-19 23:40:14.577088: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-19 23:45:03.058835: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-19 23:45:03.059069: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-19 23:51:23.100736: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-19 23:51:23.108553: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-19 23:55:24.911828: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-19 23:55:24.912000: Car 1 charging Manual SoC current is 4.04 next is 4.599
2025-11-20 00:00:38.105894: Car 0 charging Manual SoC current is 4.599 next is 4.599
2025-11-20 00:00:38.113794: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 00:05:04.019829: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 00:05:04.020002: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 00:10:17.410705: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 00:10:17.413866: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 00:15:02.983339: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 00:15:02.983491: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 00:20:14.594887: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 00:20:14.604367: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 00:25:03.171951: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 00:25:03.172097: Car 1 charging Manual SoC current is 4.04 next is 4.599
2025-11-20 00:30:53.038071: Car 0 charging Manual SoC current is 4.599 next is 4.599
2025-11-20 00:30:53.046972: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 00:35:03.702192: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 00:35:03.702359: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 00:40:19.055614: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 00:40:19.062766: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 00:45:03.871747: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 00:45:03.871898: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 00:50:15.998514: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 00:50:16.008337: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 00:55:03.957558: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 00:55:03.957745: Car 1 charging Manual SoC current is 4.04 next is 4.599
2025-11-20 01:00:30.737941: Car 0 charging Manual SoC current is 4.599 next is 4.599
2025-11-20 01:00:30.743799: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 01:05:03.395204: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 01:05:03.395355: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 01:10:23.031611: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 01:10:23.033524: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 01:15:04.784892: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 01:15:04.785061: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 01:20:15.555232: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 01:20:15.555374: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 01:25:03.208450: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 01:25:03.208621: Car 1 charging Manual SoC current is 4.04 next is 4.599
2025-11-20 01:30:27.571000: Car 0 charging Manual SoC current is 4.599 next is 4.599
2025-11-20 01:30:27.571152: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 01:35:02.843115: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 01:35:02.843266: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 01:40:17.093751: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 01:40:17.100618: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 01:45:03.805858: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 01:45:03.805995: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 01:50:13.671241: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 01:50:13.671390: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 01:55:03.218604: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 01:55:03.218789: Car 1 charging Manual SoC current is 4.04 next is 4.599
2025-11-20 02:01:31.979945: Car 0 charging Manual SoC current is 4.599 next is 4.599
2025-11-20 02:01:31.985761: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 02:05:03.485724: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 02:05:03.485893: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 02:10:47.450058: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 02:10:47.459871: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 02:15:03.863031: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 02:15:03.863183: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 02:20:35.832388: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 02:20:35.843863: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 02:25:03.568044: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 02:25:03.568301: Car 1 charging Manual SoC current is 4.04 next is 4.599
2025-11-20 02:31:00.704661: Car 0 charging Manual SoC current is 4.599 next is 4.599
2025-11-20 02:31:00.711305: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 02:35:15.047723: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 02:35:15.052362: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 02:41:00.728826: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 02:41:00.734779: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 02:45:16.098900: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 02:45:16.099143: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 02:50:43.402953: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 02:50:43.411919: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 02:55:03.348257: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 02:55:03.348491: Car 1 charging Manual SoC current is 4.04 next is 4.599
2025-11-20 03:01:52.476759: Car 0 charging Manual SoC current is 4.599 next is 4.599
2025-11-20 03:01:52.476939: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 03:05:03.261201: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 03:05:03.261367: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 03:11:15.773513: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 03:11:15.773700: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 03:15:14.399357: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 03:15:14.399530: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 03:20:17.726030: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 03:20:17.726181: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 03:25:03.047048: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 03:25:03.047217: Car 1 charging Manual SoC current is 4.04 next is 4.599
2025-11-20 03:31:03.505589: Car 0 charging Manual SoC current is 4.599 next is 4.599
2025-11-20 03:31:03.508593: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 03:35:03.091053: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 03:35:03.091243: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 03:41:11.737608: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 03:41:11.748223: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 03:45:14.389609: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 03:45:14.389798: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 03:50:30.189580: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 03:50:30.192614: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 03:55:15.451188: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 03:55:15.451340: Car 1 charging Manual SoC current is 4.04 next is 4.599
2025-11-20 04:01:53.150732: Car 0 charging Manual SoC current is 4.599 next is 4.599
2025-11-20 04:01:53.161033: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 04:05:03.656147: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 04:05:03.656311: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 04:10:38.827163: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 04:10:38.835252: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 04:15:04.697261: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 04:15:04.697424: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 04:20:17.356048: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 04:20:17.356285: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 04:25:02.953167: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 04:25:02.953319: Car 1 charging Manual SoC current is 4.04 next is 4.599
2025-11-20 04:31:07.631903: Car 0 charging Manual SoC current is 4.599 next is 4.599
2025-11-20 04:31:07.632058: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 04:35:14.139705: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 04:35:14.139859: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 04:40:39.766729: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 04:40:39.766894: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 04:45:14.674455: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 04:45:14.674664: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 04:50:27.064994: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 04:50:27.065146: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 04:55:14.909768: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 04:55:14.909916: Car 1 charging Manual SoC current is 4.04 next is 4.599
2025-11-20 05:00:53.152193: Car 0 charging Manual SoC current is 4.599 next is 4.599
2025-11-20 05:00:53.160219: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 05:05:03.484389: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 05:05:03.484560: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 05:10:16.545200: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 05:10:16.546344: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 05:15:03.046459: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 05:15:03.046610: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 05:20:17.431598: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 05:20:17.432901: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 05:25:05.329197: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 05:25:05.329342: Car 1 charging Manual SoC current is 4.04 next is 4.599
2025-11-20 05:30:38.811215: Car 0 charging Manual SoC current is 4.599 next is 4.599
2025-11-20 05:30:38.812530: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 05:35:03.150426: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 05:35:03.150676: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 05:40:16.415031: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 05:40:16.415187: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 05:45:03.859210: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 05:45:03.859364: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 05:50:16.339209: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 05:50:16.339370: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 05:55:02.835811: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 05:55:02.835975: Car 1 charging Manual SoC current is 4.04 next is 4.599
2025-11-20 06:00:27.190227: Car 0 charging Manual SoC current is 4.599 next is 4.599
2025-11-20 06:00:27.190375: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 06:05:03.630330: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 06:05:03.630496: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 06:10:16.661409: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 06:10:16.663478: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 06:15:03.399280: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 06:15:03.399433: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 06:20:15.927993: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 06:20:15.928151: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 06:25:03.440166: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 06:25:03.440335: Car 1 charging Manual SoC current is 4.04 next is 4.599
2025-11-20 06:30:27.567838: Car 0 charging Manual SoC current is 4.599 next is 4.599
2025-11-20 06:30:27.570485: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 06:35:02.911179: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 06:35:02.911342: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 06:40:17.474521: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 06:40:17.485256: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 06:45:03.330544: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 06:45:03.332983: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 06:50:17.114994: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 06:50:17.117947: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 06:55:03.987779: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 06:55:03.987949: Car 1 charging Manual SoC current is 4.04 next is 4.599
2025-11-20 07:00:32.419218: Car 0 charging Manual SoC current is 4.599 next is 4.599
2025-11-20 07:00:32.423381: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 07:05:03.163949: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 07:05:03.164099: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 07:10:16.322258: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 07:10:16.322420: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 07:15:03.796789: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 07:15:03.797026: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 07:20:16.171167: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 07:20:16.171317: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 07:25:03.800097: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 07:25:03.800248: Car 1 charging Manual SoC current is 4.04 next is 4.599
2025-11-20 07:30:27.758876: Car 0 charging Manual SoC current is 4.599 next is 4.599
2025-11-20 07:30:27.759019: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 07:35:03.132661: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 07:35:03.132828: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 07:40:15.858256: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 07:40:15.858399: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 07:45:03.231077: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 07:45:03.231216: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 07:50:16.502279: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 07:50:16.503304: Car 1 charging Manual SoC current is 4.04 next is 4.6
2025-11-20 07:55:02.983981: Car 0 charging Manual SoC current is 4.6 next is 4.6
2025-11-20 07:55:02.984137: Car 1 charging Manual SoC current is 4.04 next is 4.599
2025-11-20 08:00:49.133024: Car 0 charging Manual SoC current is 4.599 next is 4.599
2025-11-20 08:00:49.142131: Car 1 charging Manual SoC current is 4.04 next is 4.04
2025-11-20 08:05:03.743612: Car 0 charging Manual SoC current is 4.04 next is 4.04
2025-11-20 08:05:03.743796: Car 1 charging Manual SoC current is 4.04 next is 4.04
```


I can't pretend to understand how it works but it seems that every 5 minutes the CAR1 was reset to it's original value (4.04) 
So I guess each time it thinks it still needs to charge.

Also at 8am you can see that the manual SOC returns back to 4.04 (for both car). That is a different behaviour than when I use the first car profile (without your modification)
In that case the Manal SOC stays at whatever it ended the charge.

I have tried to look at the code but I have to say I don't understand the structure of it so it is difficult for me to make sense of it.

Obviously I am not here to tell you what to do but may be it would be wiser to address the main problem (only one manual SOC for both car) rather than trying to address my case.

In any case I appreciate your time and patience with me :)

**Comment by gcoan** [comment]
> Obviously I am not here to tell you what to do but may be it would be wiser to address the main problem (only one manual SOC for both car) rather than trying to address my case.
> 
> In any case I appreciate your time and patience with me :)

it was an attempt to get a quick fix to give you a manual soc for car 2, but OK, its not working.  I could keep debugging this and thinking about why it doesn't increment properly, but as you say, its probably better to focus on working out a proper solution.

Worth a try

Probably best if you revert this change and we know manual soc works fine for car 1.

I was wondering if it would be simpler to just set num_cars to 1 so Predbat thinks you only have the 1 car, and then when you want to charge car 2 you change car charging battery size and any other required car config to your second car details.   Might be the simplest way to handle things until I can work out a proper enhancement

**Comment by ppmt** [comment]
> it was an attempt to get a quick fix to give you a manual soc for car 2, but OK, its not working. I could keep debugging this and thinking about why it doesn't increment properly, but as you say, its probably better to focus on working out a proper solution.
> 
> Worth a try
As you find the time to work on the solution, I will be very happy to help you testing. Do not hesitate to ask. 

> I was wondering if it would be simpler to just set num_cars to 1 so Predbat thinks you only have the 1 car, and then when you want to charge car 2 you change car charging battery size and any other required car config to your second car details. Might be the simplest way to handle things until I can work out a proper enhancement

Funnily enough before I decided to post, I was about to do just that until I decided that surely I was the problem and I should ask :)

The other thing that stopped me was that you loose the ability to differentiate the cost of charging each car....but since I am paying the bill for both cars it is a bit of a moot point  😆 

I will do just that and will then finally release the little tutorial I was working on before all that

Thank you so much for your support

**Comment by gcoan** [comment]
I've got it on the list of things to look at, and we'll leave this issue open, but that sounds a sensible workaround for now.
There's always a spreadsheet.

**Comment by springfall2008** [comment]
Code on main for testing

**Comment by ppmt** [comment]
@springfall2008 . How can I test the code. I am using the Home Assistant Addons.

**Comment by gcoan** [comment]
> [@springfall2008](https://github.com/springfall2008) . How can I test the code. I am using the Home Assistant Addons.

use select.predbat_version and choose the option 'main' - this will auto-install the release Trefor has produced

**Comment by ppmt** [comment]
I assume you meant select.predbat_version?
I will try it tomorrow when I am home
Thanks
PS: if it works I will have to rewrite the little guide I was going to publish :)

**Comment by gcoan** [comment]
sorry, its select.predbat_update:

<img width="526" height="197" alt="Image" src="https://github.com/user-attachments/assets/9080a5b3-df4e-49f3-b970-bac72df7f6c9" />
