### ISSUE TITLE
Solar sometimes shows correctly in plan, other times stays at fixed number

### ISSUE THREAD

**Issue by Boffinboy** [springfall2008/batpred#530]
Happy Christmas! thank you for your work and making predbat available to us!

**Describe the bug**
In the plan, the PV kWh column sometimes shows a fixed value, after reaching a certain point - this continues from then onwards even through the night. I am not sure if this is being used for planning or just a display error. Usually appears to correct itself after I notice. 

**Expected behavior**
Should show forecast values 

**Predbat version**
v7.14.24 - oops realised I was on v7.14.22, will check if new PV fix has worked!

**Environment details**

- Givenergy AC3 and 9.5 battery
- HAOS running in VM on Synology NAS

**Screenshots**
“Stuck” at 0.53
![image](https://github.com/springfall2008/batpred/assets/16564352/5db9193a-276b-4aa5-9fa3-0fc52e3aacd9)

“Stuck” at 0.49
![image](https://github.com/springfall2008/batpred/assets/16564352/8d6806c0-1f75-4c85-ac5a-f34728eab1e8)

**Log file**
Not been able to capture a log when I’ve noticed it yet - what period should I capture?

**Comment by Boffinboy** [comment]
Looking at plan it does seem to be influencing it, see below where SoC looks to be increasing 

![image](https://github.com/springfall2008/batpred/assets/16564352/45da7419-72dc-4f29-b4d1-dd7caa44ed77)

**Comment by springfall2008** [comment]
Hopefully fixed now: https://github.com/springfall2008/batpred/releases/tag/v7.14.25

**Comment by Boffinboy** [comment]
Thank you. I think it may have been fixed and I’d not updated to 14.24. Have updated to 25 and will let you know!

**Comment by Boffinboy** [comment]
Looks like the issue isn’t occurring anymore! However, I am a bit puzzled by the current plan. It seems to only be doing a very small charge before the peak, despite many slots being nearly half the price of others. Even with round trip losses I would have thought it makes sense to charge? I have conservative settings for the solar because Solcast tends to significantly err on the positive for my array vs reality, and I have set a high bar for force discharge as I don’t want the extra cycles, but I am surprised there is no charging happening. 

![IMG_3124](https://github.com/springfall2008/batpred/assets/16564352/96b28e2d-3a5f-4bfe-b09e-46547bdbfafd)
![IMG_3125](https://github.com/springfall2008/batpred/assets/16564352/b6eca12d-b4c9-429e-bb2a-2e11510e8862)
![IMG_3126](https://github.com/springfall2008/batpred/assets/16564352/7a4e7b7a-93fc-4529-879f-25635782b85d)
![IMG_3127](https://github.com/springfall2008/batpred/assets/16564352/212e9f1e-274e-49da-a9ce-fe88662f5697)
![IMG_3128](https://github.com/springfall2008/batpred/assets/16564352/4a6b3c7d-89e3-46b8-8d99-1f0d004cd45e)
![IMG_3129](https://github.com/springfall2008/batpred/assets/16564352/08ed8160-672f-4ff1-92e6-44c4343f59ef)

**Comment by springfall2008** [comment]
Try setting metric soc keep to 0.5 and maybe reduce metric battery cycle back to 2?

**Comment by Boffinboy** [comment]
Setting keep to 0.4 (roughly equivalent to 4% reserve) totally transformed it back to something more like I’d expect. I’m still not entirely sure how the soc keep influences the plan - I would have thought allowing it to run to empty with would be optimal?

**Comment by springfall2008** [comment]
Was the empty plan cheaper or more expensive for the next 24 hours?

**Comment by Boffinboy** [comment]
I have to confess I didn’t check… very silly of me!

**Comment by springfall2008** [comment]
>On a somewhat related note - does metric_min_improvement_discharge relate solely to forced discharge (including export)?

It relates to forced export, and the time period is one export slot which can be normally up to 1 hour maximum bit is sized in 5 minute chunks.

**Comment by Boffinboy** [comment]
Thank you very much for the explanation. Have sent you a couple of beers. Really appreciate your work and responsiveness!
